### ISSUE TITLE
Feed pages are auto-pruned

### ISSUE THREAD

**Issue by freakboy3742** [lektor/lektor-atom#10]
Using Lektor 2.3, feeds are correctly generated - but then immediately pruned by the lektor build process. It is necessary to use the `--no-prune` option to get a working feed output.

An example project demonstrating the problem can be found in the pybee/pybee.github.io repository.

**Comment by goanpeca** [comment]
I think I have seen this happen before. Need to double check. It definitely happens on the pybee site.

**Comment by eigengrau** [comment]
I ran into this after enabling the alternatives system within Lektor. I also noticed that this does not trigger for all feeds, but only those associated with pages that exist only for the primary alternative (so, `contents.lr` exists, but `contents+en.lr` does not.

**Comment by eljoest** [comment]
I'm seeing the same problem with active alternatives. The feeds that are based on a page without translation get pruned. This happens even for the primary alternative, if there's no "(Overlaid)" content (in my case the primary is de, secondary is en. If there's no contents+de.lr the primary feed gets pruned. If there's no contents+en.lr the secondary feed gets pruned).

**Comment by mantuko** [comment]
I'm on Lektor 3.2 and my feeds still geht auto pruned.

**Comment by dwt** [comment]
I'm pretty sure the problem behind this behaviour is that the feed can't / doesn't depend on any file in the lektor source code besides the project file and thus the build system thinks the file is obsolete.

See
- https://github.com/lektor/lektor/issues/499
- https://github.com/lektor/lektor/pull/903

I'd like to tackle this, but I'm not entirely sure what the right way to go about this is. Ideas welcome.
