### ISSUE TITLE
Move to lektor organization

### ISSUE THREAD

**Issue by goanpeca** [lektor/lektor-atom#26]

**Comment by nixjdm** [comment]
Transferred

**Comment by goanpeca** [comment]
Awesome! if you could give me access I could hep with the release  ;-)

**Comment by nixjdm** [comment]
@goanpeca Sure. You should now have what you need :) This is the one that we'll put a temp werkzeug version restriction on before merging the long-term fix, to quickly unblock the website build. I was going to, but I can let you handle that if you like. I'll move on to my next to-do and circle back to do this if you haven't got to it.
