### ISSUE TITLE
Release new package

### ISSUE THREAD

**Issue by goanpeca** [lektor/lektor-atom#27]
- [ ] Update requirement on werkzeug <1 while we make a longer term fix
- [ ] Update CI to use tags as release process

**Comment by goanpeca** [comment]
Working on this today @nixjdm

**Comment by goanpeca** [comment]
I will need access to setting to pass a PyPI credential as a github secret for making the release process.

Also I might need the credentials of the getlektor pypi user for that.

**Comment by runfalk** [comment]
I think we need Owner access for that, I'd also be interested in that to investigate custom domain name support + SSL for the docs.

**Comment by goanpeca** [comment]
Released https://pypi.org/project/lektor-atom/ !

The CI worked as expected :-)
