### ISSUE TITLE
Make a new GitHub release

### ISSUE THREAD

**Issue by CAM-Gerlach** [lektor/lektor-atom#38]
Hey, thanks for finally releasing v0.4.0 on PyPI! Unfortunately, I wasn't aware of the release until I noticed a mention on another repo and manually navigated to the PyPI page, as the latest GitHub released still showed v0.3.1. Could a new release be made from the v0.4.0 tag, so people visiting here can tell at a glance that a new release was made? Thanks!

**Comment by dairiki** [comment]
Done!

**Comment by CAM-Gerlach** [comment]
Thanks!
